INSERT INTO public.role (id, name) VALUES (DEFAULT, 'admin');
INSERT INTO public.role (id, name) VALUES (DEFAULT, 'user');

INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 1, 'roby', '123', 'A', 'roby@vali-it.ee');
INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 2, 'toits666', '123', 'A', 'toivo.olen@kalamees.com');
INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 2, 'priit1', '123', 'A', 'priit@tiirp.ee');
INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 2, 'kalakunn', '123', 'A', 'jaak@hot.ee');
INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 2, 'eestlane123', '123', 'A', 'kalakala@gmail.com');
INSERT INTO public."user" (id, role_id, username, password, status, e_mail) VALUES (DEFAULT, 2, 'aHven', '123', 'A', 'ahven@salmo.ee');

INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Harku järv', 59.417966, 24.617556, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Tänavjärv', 59.182901, 23.812390, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Ermistu järv', 58.377462, 23.982515, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Pärnu jõgi', 58.420206, 24.693609, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Võrtsjärv', 58.121026, 26.085510, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Peipsi järv', 58.395300, 27.288148, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Narva veehoidla', 59.295002, 28.050041, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Kahala järv', 59.481975, 25.533975, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Karujärv', 58.383090, 22.229942, 'A');
INSERT INTO public.waterbody (id, name, latitude, longitude, status) VALUES (DEFAULT, 'Pullijärv', 57.602383, 27.215532, 'A');

INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-05-06', 1, 1, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-05-12', 1, 2, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-06-28', 1, 3, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-07-01', 1, 4, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-07-29', 2, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-08-05', 2, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-08-15', 6, 7, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-08-16', 6, 8, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-08-22', 3, 9, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-09-02', 3, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-09-08', 3, 3, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-09-11', 3, 4, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-09-30', 4, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-10-05', 4, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-10-14', 4, 7, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-10-19', 4, 1, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-10-21', 5, 2, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-10-28', 5, 3, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-11-04', 5, 4, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2022-11-09', 5, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-05-09', 6, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-05-12', 6, 7, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-09-28', 5, 8, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-01', 5, 9, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-29', 5, 10, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-08-05', 5, 1, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-08-15', 4, 2, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-08-16', 4, 3, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-08-22', 4, 4, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-09-02', 4, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-09-08', 3, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-09-11', 3, 7, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-09-30', 3, 8, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-05', 3, 9, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-14', 2, 10, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-19', 2, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-21', 1, 7, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-10-28', 1, 5, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-11-04', 1, 6, 'A');
INSERT INTO public.acatch (id, date, user_id, waterbody_id, status) VALUES (DEFAULT, '2021-11-09', 1, 7, 'A');

INSERT INTO public.species (id, name) VALUES (DEFAULT, 'koha');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'haug');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'latikas');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'kiisk');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'ahven');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'särg');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'viidikas');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'nurg');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'tint');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'luts');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'angerjas');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'säinas');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'rünt');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'linask');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'roosärg');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'hõbekoger');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'koger');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'tõugjas');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'jõeforell');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'turb');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'teib');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'karpkala');
INSERT INTO public.species (id, name) VALUES (DEFAULT, 'rääbis');

INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 22, 132, false, 'Eriti hea püük', true, null, 5, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 22, 132, false, 'Eriti hea püük', true, null, 15, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 24, 160, false, 'Eriti hea püük', true, null, 5, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 24, 160, false, 'Eriti hea püük', true, null, 20, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 31, 276, true, 'Eriti hea püük', true, null, 3, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 31, 276, true, 'Eriti hea püük', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 33, 293, true, 'Eriti hea püük', true, null, 1, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 33, 293, true, 'Eriti hea püük', true, null, 15, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 297, false, 'Eriti hea püük', true, null, 8, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 297, false, 'Eriti hea püük', true, null, 5, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 323, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 15, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 323, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 338, false, 'Pöörleva landiga', true, null, 12, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 338, false, 'Pöörleva landiga', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 361, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 15, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 361, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 15, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 381, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 381, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 36, 400, false, 'Suured kalad lõid lupsu', true, null, 5, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 36, 400, false, 'Suured kalad lõid lupsu', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 412, false, 'Palju rahvast', true, null, 15, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 412, false, 'Palju rahvast', true, null, 13, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 418, false, 'Eriti hea püük', true, null, 5, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 418, false, 'Eriti hea püük', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 62, 441, false, 'Suured kalad lõid lupsu', true, null, 15, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 62, 441, false, 'Suured kalad lõid lupsu', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 442, false, 'Põhja pealt', true, null, 12, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 442, false, 'Põhja pealt', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 62, 448, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 15, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 62, 448, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 462, false, 'Põhjaõngega püütud', true, null, 15, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 462, false, 'Põhjaõngega püütud', true, null, 20, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 493, false, 'Eriti hea püük', true, null, 8, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 493, false, 'Eriti hea püük', true, null, 7, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 500, false, 'Hommikune püük', true, null, 12, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 500, false, 'Hommikune püük', true, null, 3, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 571, false, 'Palju rahvast', true, null, 8, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 38, 571, false, 'Palju rahvast', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 582, false, 'Suured kalad lõid lupsu', true, null, 8, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 582, false, 'Suured kalad lõid lupsu', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 69, 600, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 15, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 10, 600, false, 'Eriti hea püük', true, null, 15, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 26, 600, false, 'Eriti hea püük', true, null, 15, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 69, 600, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 11, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 10, 600, false, 'Eriti hea püük', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 26, 600, false, 'Eriti hea püük', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 607, true, 'Põhja pealt', true, null, 2, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 607, true, 'Põhja pealt', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 622, true, 'Eriti hea püük', true, null, 3, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 622, true, 'Eriti hea püük', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 684, true, 'Soe, tuuline', true, null, 3, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 684, true, 'Soe, tuuline', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 709, false, 'Hommikune püük', true, null, 9, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 709, false, 'Hommikune püük', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 39, 722, false, 'Eriti hea püük', true, null, 8, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 39, 722, false, 'Eriti hea püük', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 31, 726, true, 'Eriti hea püük', true, null, 1, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 31, 726, true, 'Eriti hea püük', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 731, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', false, null, 20, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 731, false, 'Eriti hea püük', true, null, 8, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 731, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', false, null, 3, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 731, false, 'Eriti hea püük', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 33, 741, true, 'Hommikune püük', true, null, 2, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 33, 741, true, 'Hommikune püük', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 743, true, 'Eriti hea püük', true, null, 10, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 743, true, 'Eriti hea püük', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 745, false, 'Põhja pealt', true, null, 9, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 745, false, 'Põhja pealt', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 750, true, 'Hommikune püük', true, null, 14, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 750, true, 'Hommikune püük', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 758, false, 'Eriti hea püük', true, null, 11, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 758, false, 'Eriti hea püük', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 779, true, 'Põhja pealt', true, null, 11, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 779, true, 'Põhja pealt', true, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 783, true, 'Eriti hea püük', true, null, 10, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 783, true, 'Eriti hea püük', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 786, true, 'Eriti hea püük', true, null, 1, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 786, true, 'Palju rahvast', true, null, 3, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 786, true, 'Eriti hea püük', true, null, 20, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 786, true, 'Palju rahvast', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 790, true, 'Suured kalad lõid lupsu', true, null, 8, 4, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 40, 790, true, 'Suured kalad lõid lupsu', true, null, 14, 24, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 792, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 792, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 795, true, 'Eriti hea püük', true, null, 10, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 795, true, 'Eriti hea püük', true, null, 20, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 816, false, 'Eriti hea püük', true, null, 11, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 816, false, 'Eriti hea püük', true, null, 13, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 817, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 817, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 818, false, 'Soe, tuuline', true, null, 8, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 818, false, 'Soe, tuuline', true, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 823, true, 'Põhja pealt', false, null, 3, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 823, true, 'Põhja pealt', false, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 826, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 826, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 828, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 828, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 829, true, 'Palju rahvast', true, null, 10, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 829, true, 'Palju rahvast', true, null, 7, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 833, false, 'Soe, tuuline', true, null, 11, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 833, false, 'Soe, tuuline', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 834, true, 'Palju rahvast', true, null, 3, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 834, true, 'Palju rahvast', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 841, false, 'Soe, tuuline', true, null, 5, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 841, false, 'Soe, tuuline', true, null, 14, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 844, true, 'Suured kalad lõid lupsu', true, null, 10, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 844, true, 'Suured kalad lõid lupsu', true, null, 5, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 855, false, 'Eriti hea püük', true, null, 8, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 855, false, 'Eriti hea püük', true, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 867, false, 'Suured kalad lõid lupsu', true, null, 7, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 867, false, 'Suured kalad lõid lupsu', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 869, true, 'Vihmane', true, null, 14, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 41, 869, true, 'Vihmane', true, null, 15, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 871, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 871, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 3, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 876, true, 'Soe, tuuline', true, null, 14, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 876, true, 'Soe, tuuline', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 877, false, 'Soe, tuuline', true, null, 10, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 877, false, 'Soe, tuuline', true, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 891, false, 'Eriti hea püük', true, null, 8, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 891, false, 'Eriti hea püük', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 895, true, 'Eriti hea püük', true, null, 8, 5, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 895, true, 'Eriti hea püük', true, null, 13, 25, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 900, true, 'Palju rahvast', true, null, 10, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 900, true, 'Palju rahvast', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 907, false, 'Põhja pealt', true, null, 8, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 907, false, 'Põhja pealt', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 918, true, 'Palju rahvast', true, null, 14, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 918, true, 'Palju rahvast', true, null, 3, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 926, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 14, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 926, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 929, true, 'Palju rahvast', true, null, 8, 3, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 929, false, 'Palju rahvast', true, null, 12, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 929, true, 'Palju rahvast', true, null, 14, 23, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 929, false, 'Palju rahvast', true, null, 7, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 933, false, 'Palju rahvast', true, null, 11, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 933, false, 'Palju rahvast', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 936, false, 'Palju rahvast', true, null, 8, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 936, false, 'Palju rahvast', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 937, true, 'Palju rahvast', true, null, 14, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 937, true, 'Eriti hea püük', true, null, 14, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 937, true, 'Palju rahvast', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 937, true, 'Eriti hea püük', true, null, 8, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 943, true, 'Eriti hea püük', true, null, 13, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 943, true, 'Eriti hea püük', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 944, true, 'Palju rahvast', true, null, 11, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 944, true, 'Palju rahvast', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 945, true, 'Vihmane', false, null, 3, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 945, true, 'Vihmane', false, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 946, true, 'Eriti hea püük', true, null, 8, 6, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 946, true, 'Eriti hea püük', true, null, 11, 26, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 948, true, 'Eriti hea püük', true, null, 10, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 948, true, 'Eriti hea püük', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 950, true, 'Soe, tuuline', false, null, 20, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 950, true, 'Soe, tuuline', false, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 955, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 9, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 955, false, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 956, true, 'Suured kalad lõid lupsu', true, null, 10, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 956, true, 'Suured kalad lõid lupsu', true, null, 14, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 960, true, 'Suured kalad lõid lupsu', true, null, 13, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 960, true, 'Suured kalad lõid lupsu', true, null, 7, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 961, false, 'Põhjaõngega püütud', true, null, 9, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 961, true, 'Suured kalad lõid lupsu', true, null, 10, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 961, true, 'Eriti hea püük', true, null, 13, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 961, false, 'Põhjaõngega püütud', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 961, true, 'Suured kalad lõid lupsu', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 42, 961, true, 'Eriti hea püük', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 963, true, 'Eriti hea püük', true, null, 10, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 963, true, 'Eriti hea püük', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 964, true, 'Eriti hea püük', true, null, 10, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 964, true, 'Eriti hea püük', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 972, true, 'Põhjaõngega püütud', true, null, 11, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 972, true, 'Põhjaõngega püütud', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 974, true, 'Palju rahvast', true, null, 13, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 974, true, 'Palju rahvast', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 977, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 14, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 977, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 981, false, 'Eriti hea püük', true, null, 11, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 981, false, 'Eriti hea püük', true, null, 14, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 983, false, 'Eriti hea püük', true, null, 5, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 983, false, 'Eriti hea püük', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 985, false, 'Suured kalad lõid lupsu', true, null, 11, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 985, false, 'Suured kalad lõid lupsu', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 986, false, 'Suured kalad lõid lupsu', true, null, 5, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 986, false, 'Suured kalad lõid lupsu', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 998, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 998, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1001, false, 'Eriti hea püük', true, null, 8, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1001, false, 'Eriti hea püük', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1011, false, 'Palju rahvast', true, null, 5, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1011, false, 'Palju rahvast', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1012, false, 'Põhjaõngega püütud', true, null, 8, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1012, false, 'Põhjaõngega püütud', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1013, false, 'Eriti hea püük', true, null, 11, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1013, true, 'Hommikune püük', false, null, 3, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1013, false, 'Eriti hea püük', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1013, true, 'Hommikune püük', false, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1018, true, 'Eriti hea püük', true, null, 3, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1018, true, 'Eriti hea püük', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1022, true, 'Soe, tuuline', true, null, 8, 2, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1022, true, 'Soe, tuuline', true, null, 15, 22, 'D');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1027, false, 'Suured kalad lõid lupsu', true, null, 8, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1027, false, 'Suured kalad lõid lupsu', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1041, true, 'Vihmane', true, null, 10, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1041, true, 'Vihmane', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1043, false, 'Soe, tuuline', true, null, 7, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1043, false, 'Soe, tuuline', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1046, false, 'Soe, tuuline', true, null, 11, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1046, false, 'Soe, tuuline', true, null, 7, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 1050, true, 'Suured kalad lõid lupsu', true, null, 14, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 1050, true, 'Suured kalad lõid lupsu', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1051, false, 'Eriti hea püük', true, null, 11, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1051, false, 'Eriti hea püük', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1054, false, 'Eriti hea püük', true, null, 8, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1054, false, 'Eriti hea püük', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1058, true, 'Suured kalad lõid lupsu', true, null, 11, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1058, true, 'Suured kalad lõid lupsu', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1059, true, 'Soe, tuuline', true, null, 10, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1059, true, 'Soe, tuuline', true, null, 14, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 1061, true, 'Eriti hea püük', true, null, 13, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 43, 1061, true, 'Eriti hea püük', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1072, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 10, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1072, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1073, false, 'Soe, tuuline', true, null, 8, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1073, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 10, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1073, false, 'Soe, tuuline', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1073, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 3, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1074, false, 'Vihmane', true, null, 9, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1074, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 9, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1074, false, 'Vihmane', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1074, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1085, true, 'Suured kalad lõid lupsu', true, null, 14, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1085, true, 'Suured kalad lõid lupsu', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1092, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1092, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1095, false, 'Suured kalad lõid lupsu', true, null, 12, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1095, true, 'Soe, tuuline', true, null, 14, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1095, false, 'Suured kalad lõid lupsu', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1095, true, 'Soe, tuuline', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1105, true, 'Pöörleva landiga', false, null, 3, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1105, true, 'Pöörleva landiga', false, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1117, false, 'Soe, tuuline', true, null, 8, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1117, false, 'Soe, tuuline', true, null, 14, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 58, 1120, false, 'Soe, tuuline', true, null, 15, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 58, 1120, false, 'Soe, tuuline', true, null, 14, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1121, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1121, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1125, true, 'Eriti hea püük', true, null, 14, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1125, true, 'Eriti hea püük', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1126, true, 'Eriti hea püük', true, null, 14, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 44, 1126, true, 'Eriti hea püük', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1131, true, 'Soe, tuuline', true, null, 10, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1131, true, 'Soe, tuuline', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1134, true, 'Põhjaõngega püütud', false, null, 3, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 45, 1134, true, 'Põhjaõngega püütud', false, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1150, false, 'Põhja pealt', true, null, 7, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1150, false, 'Põhja pealt', true, null, 13, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1164, true, 'Soe, tuuline', true, null, 11, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1164, true, 'Soe, tuuline', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1168, true, 'Hommikune püük', true, null, 11, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1168, true, 'Hommikune püük', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1169, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 11, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1169, false, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1173, false, 'Eriti hea püük', true, null, 8, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1173, false, 'Eriti hea püük', true, null, 14, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1180, false, 'Suured kalad lõid lupsu', true, null, 8, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1180, false, 'Suured kalad lõid lupsu', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1187, false, 'Pöörleva landiga', true, null, 8, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1187, false, 'Pöörleva landiga', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1212, true, 'Suured kalad lõid lupsu', false, null, 3, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1212, true, 'Suured kalad lõid lupsu', false, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1220, true, 'Palju rahvast', true, null, 14, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1220, true, 'Palju rahvast', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1221, true, 'Soe, tuuline', true, null, 14, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1221, true, 'Soe, tuuline', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 50, 1231, false, 'Suured kalad lõid lupsu', true, null, 14, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 50, 1231, false, 'Suured kalad lõid lupsu', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1237, true, 'Pöörleva landiga', true, null, 14, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1237, true, 'Pöörleva landiga', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1239, true, 'Palju rahvast', true, null, 10, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1239, true, 'Palju rahvast', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1246, true, 'Väljas väga külm, aga vesi veel soe.', false, null, 20, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1246, true, 'Väljas väga külm, aga vesi veel soe.', false, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1250, true, 'Soe, tuuline', true, null, 13, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1250, true, 'Soe, tuuline', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 1251, true, 'Põhjaõngega püütud', true, null, 2, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 1251, true, 'Põhjaõngega püütud', true, null, 13, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1262, true, 'Eriti hea püük', true, null, 10, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1262, true, 'Eriti hea püük', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1279, false, 'Palju rahvast', true, null, 8, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1279, false, 'Palju rahvast', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1282, true, 'Pöörleva landiga', true, null, 11, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1282, true, 'Pöörleva landiga', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1285, false, 'Vihmane', true, null, 8, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1285, false, 'Vihmane', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1290, false, 'Hommikune püük', true, null, 7, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1290, false, 'Hommikune püük', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1296, true, 'Eriti hea püük', true, null, 13, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1296, true, 'Eriti hea püük', true, null, 2, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1308, true, 'Soe, tuuline', true, null, 3, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 46, 1308, true, 'Soe, tuuline', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1316, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 14, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1316, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1318, true, 'Palju rahvast', true, null, 2, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1318, true, 'Palju rahvast', true, null, 2, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1319, true, 'Eriti hea püük', true, null, 1, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1319, true, 'Eriti hea püük', true, null, 13, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1332, true, 'Palju rahvast', false, null, 20, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1332, true, 'Palju rahvast', false, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1337, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 14, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1337, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1343, false, 'Vihmane', true, null, 12, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1343, false, 'Vihmane', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1352, true, 'Põhjaõngega püütud', true, null, 14, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1352, true, 'Põhjaõngega püütud', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1353, false, 'Hommikune püük', true, null, 8, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1353, false, 'Hommikune püük', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 1357, true, 'Pöörleva landiga', true, null, 2, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 1357, true, 'Pöörleva landiga', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1363, false, 'Vihmane', true, null, 7, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 47, 1363, false, 'Vihmane', true, null, 14, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1367, false, 'Pöörleva landiga', true, null, 9, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1367, false, 'Pöörleva landiga', true, null, 9, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1425, false, 'Soe, tuuline', true, null, 8, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1425, false, 'Soe, tuuline', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 1431, false, 'Pöörleva landiga', true, null, 7, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 37, 1431, false, 'Pöörleva landiga', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1432, false, 'Põhjaõngega püütud', true, null, 8, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1432, false, 'Põhjaõngega püütud', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1443, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1443, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 14, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1445, true, 'Suured kalad lõid lupsu', true, null, 1, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1445, true, 'Suured kalad lõid lupsu', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1449, true, 'Suured kalad lõid lupsu', true, null, 2, 19, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1449, true, 'Suured kalad lõid lupsu', true, null, 2, 39, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1456, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 2, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1456, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 1480, false, 'Palju rahvast', true, null, 5, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 53, 1480, false, 'Palju rahvast', true, null, 2, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 1500, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 11, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 52, 1500, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 2, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1501, false, 'Palju rahvast', true, null, 7, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1501, false, 'Palju rahvast', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1544, false, 'Eriti hea püük', true, null, 15, 11, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 48, 1544, false, 'Eriti hea püük', true, null, 8, 31, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 54, 1571, true, 'Eriti hea püük', true, null, 1, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 54, 1571, true, 'Eriti hea püük', true, null, 12, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1601, true, 'Põhja pealt', true, null, 14, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1601, true, 'Põhja pealt', true, null, 13, 24, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1602, true, 'Pöörleva landiga', true, null, 2, 13, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1602, true, 'Pöörleva landiga', true, null, 8, 33, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 56, 1610, true, 'Vihmane', true, null, 1, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 56, 1610, true, 'Vihmane', true, null, 8, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1632, true, 'Palju rahvast', true, null, 1, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1632, false, 'Eriti hea püük', true, null, 11, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1632, true, 'Palju rahvast', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 49, 1632, false, 'Eriti hea püük', true, null, 8, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1738, false, 'Eriti hea püük', true, null, 8, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 51, 1738, false, 'Eriti hea püük', true, null, 14, 23, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 1812, true, 'Eriti hea püük', true, null, 3, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 1812, true, 'Eriti hea püük', true, null, 3, 37, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 57, 1848, true, 'Soe, tuuline', true, null, 1, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 57, 1848, true, 'Soe, tuuline', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 56, 1886, true, 'Eriti hea püük', true, null, 3, 10, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 56, 1886, true, 'Eriti hea püük', true, null, 8, 30, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1902, false, 'Eriti hea püük', true, null, 11, 12, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 55, 1902, false, 'Eriti hea püük', true, null, 8, 32, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 1928, true, 'Eriti hea püük', true, null, 3, 16, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 1928, true, 'Eriti hea püük', true, null, 3, 36, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 1941, true, 'Vihmane', true, null, 2, 20, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 1941, true, 'Vihmane', true, null, 1, 40, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 59, 1982, true, 'Suured kalad lõid lupsu', true, null, 3, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 59, 1982, true, 'Suured kalad lõid lupsu', true, null, 7, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 59, 1995, true, 'Eriti hea püük', true, null, 3, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 59, 1995, true, 'Eriti hea püük', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 2081, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 2, 5, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 60, 2081, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 11, 25, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 2089, true, 'Eriti hea püük', true, null, 3, 18, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 2089, true, 'Eriti hea püük', true, null, 2, 38, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 2149, true, 'Eriti hea püük', true, null, 3, 7, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 2149, true, 'Eriti hea püük', true, null, 11, 27, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 68, 2194, true, 'Eriti hea püük', true, null, 3, 9, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 68, 2194, true, 'Eriti hea püük', true, null, 10, 29, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 70, 2225, true, 'Eriti hea püük', true, null, 1, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 70, 2225, true, 'Eriti hea püük', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 71, 2416, true, 'Hommikune püük', true, null, 2, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 71, 2416, true, 'Hommikune püük', true, null, 15, 21, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2912, true, 'Eriti hea püük', true, null, 3, 8, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2912, true, 'Eriti hea püük', true, null, 10, 28, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2984, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 2, 15, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2984, true, 'Väljas väga külm, aga vesi veel soe.', true, null, 5, 35, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2991, true, 'Põhjaõngega püütud', true, null, 2, 14, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 65, 2991, true, 'Põhjaõngega püütud', true, null, 7, 34, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 66, 3091, true, 'Põhja pealt', true, null, 2, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 66, 3091, true, 'Põhja pealt', true, null, 14, 22, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 3144, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 3, 6, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 67, 3144, true, 'Õhtupoolikul enne päikeseloojangut roostiku tagant.', true, null, 11, 26, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 70, 3587, true, 'Soe, tuuline', true, null, 2, 17, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 70, 3587, true, 'Soe, tuuline', true, null, 3, 37, 'A');

INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 10, 70, true, 'kuradi kilu, lendas tagasi', true, 'asd', 7, 1, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 20, 200, false, 'hea snäkk', true, 'asd', 14, 2, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 30, 1200, false, 'salakojhast võtsin, ei näita', false, 'asd', 23, 3, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 80, 6500, false, 'Ahhsamait, vaadake seda', true, 'asd', 17, 4, 'A');
INSERT INTO public.fish (id, length, weight, released, comment, public, picture, species_id, acatch_id, status) VALUES (DEFAULT, 15, 220, false, 'ka suht ok', true, 'asd', 12, 4, 'A');